apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-spring
spec:
  selector:
    matchLabels:
      app: api-spring
  replicas: 7
  template:
    metadata:
      labels:
        app: api-spring
    spec:
      containers:
        - name: springboot-api-tienda
          image: saraymf/api-spring:latest
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: springboot-api-svc
spec:
  selector:
    app: api-spring
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort