version: "3.7"

services:
  mysql:
    container_name: mysql-db
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
      - ./tienda_discos.sql:/docker-entrypoint-initdb.d/tienda_discos.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: tienda_discos

  myapp-main:
    image: app-spring
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=pass
      - DATABASE_NAME=tienda_discos
      - DATABASE_PORT=3306